AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with one subnet for an EC2 instance, named based on the environment.

Parameters:
  Environment:
    Type: String
    Description: "The environment name (e.g., development, production)"
    AllowedValues:
      - development
      - production
      - default
    
  VpcCIDR:
    Type: String
    Description: "The IP Address range of this VPC"
    Default: '192.168.0.0/16'
  
  EC2SubnetCIDR:
    Type: String
    Description: "The IP Address range of the subnet that hosts the EC2 instance."
    Default: '192.168.1.0/24'

  EC2SubnetAZ:
    Type: String
    Description: "Availability Zone of the EC2 Subnet"
    Default: 'us-west-2a'

  SGName:
    Type: String
    Description: "Name of the security group attached to the EC2 instance."
    Default: 'S2SEC2SG'

Resources:
  
  #Create VPC with dynamic name based on the environment
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 'VPC_${Environment}'
        - Key: Environment
          Value: !Ref Environment 

  # Create a Subnet inside the VPC
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref EC2SubnetCIDR
      AvailabilityZone: !Ref EC2SubnetAZ
      Tags:
        - Key: Name
          Value: !Sub 'EC2Subnet_${Environment}'
        - Key: Environment
          Value: !Ref Environment
    DependsOn: MyVPC

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for EC2 instances"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'       
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: !Sub '${SGName}_${Environment}'

  VPCEndpointSSM:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName:
        Fn::Sub: "com.amazonaws.${AWS::Region}.ec2messages"
      VpcId: !Ref MyVPC
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref MySubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
    DependsOn:
      - MySubnet
      - EC2SecurityGroup

  VPCEndpointSSMMessages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName:
        Fn::Sub: "com.amazonaws.${AWS::Region}.ssmmessages"
      VpcId: !Ref MyVPC
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref MySubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
    DependsOn:
      - MySubnet
      - EC2SecurityGroup

  VPCEndpointEC2Messages:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: 
        Fn::Sub: "ec2messages.${AWS::Region}.amazonaws.com"
      VpcId: !Ref MyVPC
      SubnetIds:
        - !Ref MySubnet
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
    DependsOn:
      - MySubnet
      - EC2SecurityGroup

Outputs:
  VPCId:
    Description: 'The ID of the created VPC'
    Value: !Ref MyVPC
  SubnetId:
    Description: 'The ID of the created Subnet'
    Value: !Ref MySubnet
  SecurityGroupId:
    Description: 'The ID of the EC2 Security Group'
    Value: !Ref EC2SecurityGroup